# Generated by Django 5.1.3 on 2024-11-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2chatbot', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='question_id',
            field=models.IntegerField(default=1),
        ),
    ]
